<?php

namespace Fan\LawnBotBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LawnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LawnRepository extends EntityRepository
{
}
